### ISSUE TITLE
keter failing to deliver content on load "peaks"

### ISSUE THREAD

**Issue by jgreve-github** [snoyberg/keter#75] opened 2015-02-27 17:24 UTC
When refreshing a keter-deployed yesod webapp rapidly, keter fails to deliver content, bailing out with

    Error connecting to gateway:
    
    InvalidStatusLine "0"

This seems to be indepent of ssl, I tested both. Take a look at a quite raw out-of-the-box-stripped-down example at http://phreeknet.de -- refreshing this repeatedly results in sometimes no css (due to this problem) and sometime no html, instead the following message.
because keter does not seem to bind the hosted web app's 'real' instance to localhost, the raw yesod instance can be accessed at http://phreeknet.de:43125. There, only the css problem occurs (because that still gets served via keter), which sorts out the yesod instance itself as the problem.

I suspect this not only happens on rapid refresh but also on load "peaks", whereas if some clients simultaneously request data.

Please let me know if you need any further information.

    $ bin/keter --version
    keter version: 1.3.8

Great work so far, though :)

Jan

**Comment by creichert** [comment] 2015-02-27 17:35
Interesting, I haven't experienced this. It seems related to https://github.com/yesodweb/wai/issues/249 and maybe https://github.com/yesodweb/wai/issues/266.

I have quite a few sites up with Keter now and I can't reproduce this on a single one. I can reproduce it on your site, though.

It would be nice if you could provide the source for a Keter bundle we can reproduce the issue with.

**Comment by creichert** [comment] 2015-02-27 17:40
Can you verify which version of `warp-tls`, `warp` and `wai` you have installed?

**Comment by creichert** [comment] 2015-02-27 17:54
One more note. I think the cause is the chunked transfer-encoding (as stated by the issue). Once we can verify your versions I can look at possibly pinning the version to incorporate the fix in warp-tls. It does look like you are using a pretty new version of Warp, though.

**Comment by jgreve-github** [comment] 2015-02-28 12:45
The following versions are installed in the sandbox that compiled keter:

    warp-3.0.9.2
    warp-tls-3.0.2
    wai-3.0.2.3

As to the yesod source, I will tar it, upload it and post a link here, yet: it is yesod init --bare, I only edited the homepage.hamlet file, the homepage.julius file and removed the route and handler for posting to /.

**Comment by jgreve-github** [comment] 2015-02-28 12:54
A link to the demo source requested is here: https://www.dropbox.com/s/40n988dg84z31r4/demosource.tgz?dl=0

This is a full snapshot of the directory the yesod instance is at home for development. As soon as the upload is complete, the link should be working fine. Please let me know when I can remove the file again.

**Comment by jgreve-github** [comment] 2015-03-01 10:59
BTW, I re-enabled ssl and it feels like this increases the probability of bailing out. I thus suspect some sort of a timing problem.

**Comment by creichert** [comment] 2015-03-02 16:26
@snoyberg do you think this is related to https://github.com/yesodweb/wai/issues/249? He seems to have an up-to-date warp and warp-tls.

**Comment by snoyberg** [comment] 2015-03-02 16:52
It sounds more likely to be a bug in http-client; it looks like with connection sharing in the connection manager, the final chunked header is not being flushed from the socket and is being read as the first chunk in the next connection. I *did* recently fix a bug or two in shared connection, can you confirm the version of http-client, http-client-tls, and http-conduit used to build keter?

**Comment by snoyberg** [comment] 2015-03-02 16:57
@creichert The issue you linked to could theoretically be related, but it's highly unlikely. That was a very specific and ugly bug that should be completely fixed.

**Comment by jgreve-github** [comment] 2015-03-02 21:02
@snoyberg, here you go:
    http-client-0.4.7.1
    http-client-tls-0.2.2
    http-conduit-2.1.5

**Comment by jgreve-github** [comment] 2015-03-02 21:17
By the way, I noticed this also happens with yesod devel; without the yesod instance going down for compile, the site refreshing and dishing out motivational messages comes up sometimes.

I suspect that the development server is (partly) using the same technique keter does. Maybe that info helps narrowing it down further. The http-* versions are the same as for the keter sandbox.

**Comment by snoyberg** [comment] 2015-03-03 07:41
You're correct in your guess, it's mostly handled by the http-reverse-proxy library.

It's going to be difficult to debug this, as I've never encountered these issues myself, and can't reproduce them on my system. I'd like to start off by narrowing down where the problem is. I've pushed a commit to the separate-manager branch of keter, which uses a separate connection manager for each request. It's a huge pessimization, and therefore shouldn't be released, but if it solves the issue for you, it will give us a much better idea of where the bug is coming from.

Can you try using that version of keter and see what happens?

**Comment by jgreve-github** [comment] 2015-03-03 18:28
@snoyberg, I cloned the repo, switched branches and compiled, deployed and: everything seems fine.

**Comment by snoyberg** [comment] 2015-03-03 18:31
OK, so then this is seemingly an http-client bug. Next step will be
creating a reproducing test case. I'll see if I can put something together
tomorrow. If I can't reproduce, I may ask you to try running such a program
on your system.

**Comment by jgreve-github** [comment] 2015-03-03 18:37
@snoyberg, you mentioned you were not able to reproduce on your system; I cleaned up everything before, so a vanilla current Haskell-platform and a "cabal sandbox init;cabal install keter" should work for reproducing. It's a vanilla, up-to-date Ubuntu amd64 lts on both my dev server and phreeknet.de.

**Comment by snoyberg** [comment] 2015-03-03 18:41
This is most likely a race condition, which means that it's not just a
software issue, but a hardware-triggered issue.

**Comment by jgreve-github** [comment] 2015-03-03 21:41
I see. Both my dev server (a atom) and phreeknet.de (a tiny vserver) experience this. Would be a strange coincidence that both environments are affected.

**Comment by snoyberg** [comment] 2015-03-08 06:28
I'm investigating a different avenue entirely right now: the 416 status codes on one of the static/tmp files. That looks like it may be contributing significantly to the problem.

**Comment by snoyberg** [comment] 2015-03-08 07:18
OK, apologies for the mis-diagnosis, this was all because of a bad commit I merged into warp a month back. The bug should now be completely fixed in warp 3.0.9.3. You'll need to update your project to use the new version of warp. Upgrading keter should be neither necessary nor sufficient (though upgrading isn't a bad idea). Can you give that a shot and let me know if it fixes your problem? I can no longer reproduce any of the symptoms I saw on my machine.

**Comment by creichert** [comment] 2015-07-25 00:20
@jgreve-github I'm going to close this issue, please don't hesitate to reopen if the issue persists.

**Closed by creichert** 2015-07-25 00:20 UTC
Labels: bug
