### ISSUE TITLE
Install script continues despite errors

### ISSUE THREAD

**Issue by nh2** [snoyberg/keter#179] opened 2018-01-16 09:58 UTC
In my case I'm running in an Ubuntu 16.04 docker container which doesn't have `lsb_release` (see line `bash: line 8: lsb_release: command not found`); nevertheless the script continues, then giving me a confusing error message.

Likely, it should use `set -e` to not continue past errors.

```
root@b9476a3a6acb:/# wget -O - https://raw.githubusercontent.com/snoyberg/keter/master/setup-keter.sh | bash
...
+ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442
Executing: /tmp/tmp.5dMM3Hgm6I/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
575159689BEFB442
gpg: requesting key 9BEFB442 from hkp server keyserver.ubuntu.com
gpg: key 9BEFB442: public key "FPComplete <dev@fpcomplete.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
+ sudo tee /etc/apt/sources.list.d/fpco.list
++ lsb_release -sc
bash: line 8: lsb_release: command not found
+ echo 'deb http://download.fpcomplete.com/ubuntu "" main'
deb http://download.fpcomplete.com/ubuntu "" main
+ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease               
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease                       
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease                     
Ign:5 http://download.fpcomplete.com/ubuntu  InRelease                              
Ign:6 http://download.fpcomplete.com/ubuntu  Release
Ign:7 http://download.fpcomplete.com/ubuntu /main amd64 Packages
Ign:8 http://download.fpcomplete.com/ubuntu /main all Packages
Ign:7 http://download.fpcomplete.com/ubuntu /main amd64 Packages
Ign:8 http://download.fpcomplete.com/ubuntu /main all Packages
Ign:7 http://download.fpcomplete.com/ubuntu /main amd64 Packages
Ign:8 http://download.fpcomplete.com/ubuntu /main all Packages
Ign:7 http://download.fpcomplete.com/ubuntu /main amd64 Packages
Ign:8 http://download.fpcomplete.com/ubuntu /main all Packages
Ign:7 http://download.fpcomplete.com/ubuntu /main amd64 Packages
Ign:8 http://download.fpcomplete.com/ubuntu /main all Packages
Err:7 http://download.fpcomplete.com/ubuntu /main amd64 Packages
  403  Forbidden [IP: 52.72.159.235 80]
Ign:8 http://download.fpcomplete.com/ubuntu /main all Packages
Reading package lists... Done
W: The repository 'http://download.fpcomplete.com/ubuntu  Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://download.fpcomplete.com/ubuntu/dists//main/binary-amd64/Packages  403  Forbidden [IP: 52.72.159.235 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by creichert** [comment] 2018-06-21 18:00
The problem is how the shell interprets the sub-shell exit code. It's quite complicated, however, this can be trivially fixed by assigning the output of `lsb_release` to a variable. e.g. `LSB_RELEASE=$(lsb_release -sc)`


To demonstrate:

```$ echo "HI $(command_not_found)"
bash: command_not_found: command not found
HI 
$ echo $?
0
$ false
$ echo $?
1
$ echo "HI $(false)"
HI 
$ echo $?
0
$ LSB_RELEASE=$(false)
$ echo $?
1
```

So you're patch setting `set -e` is the same as `set -o errexit` and won't work. If you're still using  keter and managed to get it installed, I would be happy to merge a pull request fixing this.

**Closed by creichert** 2018-06-21 18:00 UTC

**Comment by nh2** [comment] 2018-06-24 14:19
> So you're patch setting set -e is the same as set -o errexit and won't work.

Good point!

> If you're still using keter and managed to get it installed, I would be happy to merge a pull request fixing this.

Here we go: #185
