### ISSUE TITLE
Configurable Postgres Server host / port

### ISSUE THREAD

**Issue by bermanjosh** [snoyberg/keter#100] opened 2015-06-08 09:31 UTC
Howdy,

Based on what I understood from `Keter.Plugin.Postgres.edbiToEnv`, it seems to keter is hardcoded to access postgres on localhost using it's default port. I'd like to make that configurable, to allow us to connect to a separate DB server. (I apologize if it already is & I'm missing something). 

I'd like to do a PR for this, but I'd appreciate some input on the best way to manage this, especially within the plugin-framework. Should it be per-app, (that is, any given app can access a different DB server), or per-keter (that is, every app this keter is managing access the same DB server). 

If per-app, where should this configuration info be stored? Should the `Keter.Types.Common.Plugin` be expanded? Perhaps changing pluginGetEnv's 2nd argument from a Object to a type which includes the plugin name and some config info? 

If per-keter, where should we set this info? I understand the postgress.yaml is dynamically managed, so I'm assuming we don't want to change that. My feeling is it's natural place is keter-config.yaml, but doesn't that break the plugin independence? 

Thanks for your help

**Comment by creichert** [comment] 2015-06-08 20:33
My first suggestion would be to go per-bundle. Your ideas all sound
reasonable and I wouldn't be opposed to changing `pluginGetEnv` if it
added more flexibility for future plugins.

The path of least resistance would probably be to check for a nested
Object in `pluginGetEnv` (instead of Bool), while still falling back to
the base `postgres: true` syntax.

https://github.com/snoyberg/keter/blob/c161596ab2476ee3e2850e832d9ac091c88c9c21/Keter/Plugin/Postgres.hs#L106

e.g.

```
postgres: true
```

or

```
postgres:
  - host: newhost
    port: 9999
```

The latter implying `postgres: true`.

I'm definitely open to other suggestions if you find there is a better
way, though.

**Comment by bermanjosh** [comment] 2015-06-09 06:42
@creichert, thanks for the input. I like your nested Object idea. I'll tinker around with it and try to get a PR in by the end of the week. 
Thanks!

**Comment by ygale** [comment] 2015-06-10 08:12
The problem is that to "connect to a separate DB server", we would then create a dependency of keter on `postgresql-libpq` and/or `postgresql-simple`.

Well. We could use the same hack we use now, shelling out to the `psql` command. But here that would be really silly - you would be requiring the user to install an entire PostgreSQL DB system on the web server to make the `psql` command available, when the whole point is that we want the DB to run on a *different* server.

Anyway it would be good if we could get rid of that ugly hack altogether. It doesn't even work on some platforms - e.g., RHEL with typical enterprise ACL settings does not allow `keter` to run `sudo`.

So maybe it's time to flesh out the idea of keter plugins. What would the UI be for selecting various plugins, each with its own dependencies, from Hackage *a la carte*, and getting them all to compile together into a `keter` executable?

Alternatively, we could remove the postgres plugin from the core `keter` package and have a separate `keter-postgresql` package that depends on `postgresql-simple` and provides a `keter` with the plugin. That would get rid of the hack, and also enable other configurations such as a separate DB server.

**Comment by creichert** [comment] 2015-06-17 16:50
Merged, nice work!

**Closed by creichert** 2015-06-17 16:50 UTC
