### ISSUE TITLE
hs-tls exceptions are not displayed in the log

### ISSUE THREAD

**Issue by chreekat** [snoyberg/keter#110] opened 2015-07-01 17:29 UTC
I apologize for not having a good test case handy, but I experienced this when setting up Snowdrift.coop recently. Running keter as an upstart task gave me no information, but running it manually on the shell caused

 "no ciphers available with those parameters"

to be printed out.

That message appears to come from https://github.com/vincenthz/hs-tls/blob/master/core/Network/TLS/Context.hs#L149

**Comment by creichert** [comment] 2015-07-01 17:47
Can you look through issue #39 and determine if anything mentioned there
helps (or even if it's the same issue). Ideally, we can find a way to
reproduce the issue.

As a sanity check, are you using a chain cert?

**Comment by chreekat** [comment] 2015-07-01 18:12
I think I have the exact same problem that @sajith has.

This issue is that it took me a while to figure out that something was wrong since there was no logging of the error.

**Comment by creichert** [comment] 2015-07-01 18:52
I'm not familiar with upstart but I'm wondering why the error was suppressed and if there is anything we can do about it.

Was the problem no logged to the keter logging file or are you expecting the output in the system logs?

**Comment by chreekat** [comment] 2015-07-01 19:09
The error wasn't logged to the keter logging file. It is possible that upstart should have been configured to send stdout/stderr to the system logs, but wasn't. I just copied the config from the README. Oh, in fact, there's a line 'console none' in the example upstart configuration. I imagine that line is suppressing keter's stderr.

I sort of want to call this 'user error', except it may bite others, too. Perhaps that line in the upstart should be changed to 'console output', based on a quick reading of init(5).

**Comment by creichert** [comment] 2015-07-02 07:01
Can you possibly give it a test to see if that works? If so, I see no
reason not to update the value in the README so this isn't a problem for
anyone in the future. Thanks for looking into it.

**Comment by chreekat** [comment] 2015-07-02 15:29
I'm now using 'console output' with no ill effect, though I can't
immediately test to see if the error message pops out as desired. I'm
willing to just make the change in the README and close this issue, unless
that feels a little too fast and loose.

**Comment by creichert** [comment] 2015-07-02 17:00
I think the original motivation for using console none was that keter
will log to it's own log file anyways (./log/keter/current.log). Using
any other value for console in the upstart script will duplicate the
log.

I think adding a comment above the current line in the upstart script
saying to use console output or console log if getting output into the
upstart logs is desired would be good. It might be confusing that the
apps output is not also logged there.

**Comment by creichert** [comment] 2015-07-03 15:33
I'm going ahead and closing this one since there seem to be no pending issues atm. Feel free to reopen if I missed anything.

**Closed by creichert** 2015-07-03 15:33 UTC
